config/routes.rb
Rails.application.routes.draw do
  get 'tickets/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :cars
  resources :parkings
  resources :spots
  resources :tickets do 
    put :checkout, on: :member
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
	has_many :tickets 
	has_many :spots, through: :tickets

	validates :color, presence: true
	validates :registration_number, presence: true, uniqueness: true

	scope :not_in_parking, -> {includes(:spots).where(spots: {occupied: [false, nil ]})}
end

app/models/parking.rb
class Parking < ApplicationRecord
	has_many :spots
	validates :name, presence: true 
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :parking
  has_many :tickets
  has_many :cars, through: :tickets

  validates_uniqueness_of :name, scope: :parking_id
  validates :nearest_entry, presence: true

  scope :nearest_unoccupied, -> (parking_id) {where(parking_id: parking_id, occupied: false)}
end

app/models/ticket.rb
class Ticket < ApplicationRecord

  attr_accessor :parking

  belongs_to :spot
  belongs_to :car
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def after_sign_in_path_for(resource)
	  user_path(resource)
	end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[show edit update destroy]

  def index
    respond_to do |car|
      car.html{
        @cars = Car.all.order("created_at DESC")
      }

      car.json{
        #render json: Car.all.order("created_at DESC")
        render json: Car.all, status: 200
      }
    end
    #@cars = Car.all
    #render json: @cars, status: 200
  end

  def new
    @car = Car.new
  end

  def create 
    @car = Car.new(car_params)
    if @car.save
      redirect_to cars_path, notice: 'Car has been created successfully', status: :created
    else
      render :new 
    end
  end

  def show 
  end

  def edit 
  end

  def update 
    if @car.update(car_params)
      redirect_to car_path(@car), notice: 'Cast has been updated successfully', status: :ok
    else 
      render edit 
    end
  end

  def destroy
    @car.destroy 
    redirect_to cars_path, notice: 'Car has been deleted successfully', status: :ok
  end

  private 
  def car_params 
    params.require(:car).permit(:color, :registration_number)
  end

  def set_car
    @car = Car.find(params[:id])
  end
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  before_action :set_parking, only: %i[show edit update destroy]

  def index
    @parkings = Parking.all
    render json: @parkings, status: 200
  end

  def new
    @parking = Parking.new
  end

  def create 
    @parking = Parking.new(parking_params)
    if @parking.save 
      redirect_to parkings_path, notice: 'Parking has been created successfully', status: :created
    else
      render :new 
    end
  end

  def show 
  end

  def edit 
  end

  def update 
    if @parking.update(parking_params)
      redirect_to parking_path(@parking), notice: 'Parking has been updated successfully', status: :ok
    else 
      render edit 
    end
  end

  def destroy 
    @parking.destroy 
    redirect_to parkings_path, notice: 'Parking has been deleted successfully', status: :ok
  end

  private
  def parking_params
    params.require(:parking).permit(:name)
  end

  def set_parking 
    @parking = Parking.find(params[:id])
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
	before_action :set_spot, only: %i[show edit update destroy]
	def index 
		@spots = Spot.all
    render json: @cars, status: 200
	end

	def new 
		@spot = Spot.new
	end

	def create 
    @spot = Spot.new(spot_params)
    if @spot.save 
      redirect_to spots_path, notice: 'Spot has been created successfully', status: :created
    else
      render :new 
    end
  end

  def show
  end

  def edit
  end

  def update 
    if @spot.update(spot_params)
      redirect_to spot_path(@spot)
    else 
      render edit 
    end
  end

  def destroy 
    @spot.destroy 
    redirect_to spots_path
  end


  private
  def spot_params 
  	params.require(:spot).permit(:name, :nearest_entry, :occupied, :parking_id)
  end

  def set_spot 
    @spot = Spot.find(params[:id])
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[show edit update destroy]

  def index
    @tickets = Ticket.all
  end

  def new 
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.time_arrival = Time.now
    @ticket.ticket_number = SecureRandom.hex(3)
    @ticket.spot_id = Spot.nearest_unoccupied(params[:ticket][:parking]).order(:nearest_entry).first.id
    if @ticket.save
      @ticket.spot.update(occupied: true)
      redirect_to tickets_path 
    else
      render :new 
    end
  end

  def show 
  end

  def edit 
  end

  def update 
    if @ticket.update(ticket_params)
      redirect_to ticket_path(@ticket)
    else 
      render edit 
    end
  end

  def destroy 
    @ticket.destroy 
    redirect_to tickets_path
  end

  def checkout 
    ticket = Ticket.find_by(id: params[:id])
    ticket.update(time_departure: Time.now) 
    debugger
    ticket.spot.update(occupied: false)
    redirect_to tickets_path
  end


  private
  def ticket_params 
    params.require(:ticket).permit(:time_arrival, :time_departure, :ticket_number, :spot_id, :car_id, :parking)
  end

  def set_ticket 
    @ticket = Ticket.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def parking_options
		Parking.all.map {|v| [v.name, v.id] if v.spots.present? }
	end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/parkings_helper.rb
module ParkingsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/cars/_form.html.erb
<%= form_with model: car do |form| %>

	<% if @car.errors.any? %>
		<% @car.errors.full_messages.each do |message| %>
			<p><%= message %></p>
		<% end %>
	<% end %>

	<div>
		<%= form.label :color %>
		<%= form.text_field :color %>
	</div><br> 
	<div>
		<%= form.label :registration_number %>
		<%= form.text_field :registration_number %>
	</div>

	<div>
		<%= form.submit %>
	</div>
	
<% end %>

app/views/cars/edit.html.erb
<h1>Edit Car</h1>

<%= render "form", car: @car %>

app/views/cars/index.html.erb
<h1>All Cars</h1>
<%= link_to 'New Car', new_car_path %>
<table>
	<thead>
		<tr>
			<th>Car Color</th>
			<th>Registration Number</th>
			<th colspan="3">Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @cars.each do |car| %>
			<tr>
				<td><%= car.color %></td>
				<td><%= car.registration_number %></td>
				<td><%= link_to 'View', car %></td>
				<td><%= link_to 'Edit', edit_car_path(car) %></td>
				<td><%= link_to 'Delete', car, data: { "turbo-method": :delete } %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render "form", car: @car %>

app/views/cars/show.html.erb
<h1>Car details</h1>

<p><strong>Car Color: </strong><%= @car.color %></p>
<p><strong>Registration Number: </strong><%= @car.registration_number %></p>

<%= link_to 'Back', cars_path %> | <td><%= link_to 'Edit', edit_car_path(@car) %></td>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParkingLot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/parkings/_form.html.erb
<%= form_with model: parking do |form| %>

	<% if @parking.errors.any? %>
		<% @parking.errors.full_messages.each do |message| %>
			<p><%= message %></p>
		<% end %>
	<% end %>

	<div>
		<%= form.label :name %>
		<%= form.text_field :name %>
	</div>

	<div>
		<%= form.submit %>
	</div>
	
<% end %>

app/views/parkings/edit.html.erb
<h1>Edit parking</h1>

<%= render "form", parking: @parking %>

app/views/parkings/index.html.erb
<h1>parking list</h1>
<%= link_to 'New Parking', new_parking_path %>
<table>
	<thead>
		<tr>
			<th>Parking Name</th>
			<th colspan="3">Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @parkings.each do |parking| %>
			<tr>
				<td><%= parking.name %></td>
				<td><%= link_to 'View', parking %></td>
				<td><%= link_to 'Edit', edit_parking_path(parking) %></td>
				<td><%= link_to 'Delete', parking, data: { "turbo-method": :delete } %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/parkings/new.html.erb
<h1>new parking</h1>

<%= render "form", parking: @parking %>

app/views/parkings/show.html.erb
<h1>parking details</h1>

<p><strong>Parking Name: </strong><%= @parking.name %></p>

<%= link_to 'Back', parkings_path %> | <td><%= link_to 'Edit', edit_parking_path(@parking) %></td>

app/views/spots/_form.html.erb
<%= form_with model: spot do |form| %>

	<% if @spot.errors.any? %>
		<% @spot.errors.full_messages.each do |message| %>
			<p><%= message %></p>
		<% end %>
	<% end %>

	<div>
		<%= form.label :parking_id %>
		<%= form.collection_select :parking_id, Parking.order(:name), :id, :name, include_blank: true %>
	</div><br>

	<div>
		<%= form.label :name %>
		<%= form.text_field :name %>
	</div><br>
	<div>
		<%= form.label :nearest_entry %>
		<%= form.number_field :nearest_entry %>
	</div><br>
	<div>
		<%= form.submit %>
	</div>
	
<% end %>

app/views/spots/edit.html.erb
<h1>Edit spot</h1>

<%= render "form", spot: @spot %>

app/views/spots/index.html.erb
<h1>spot list</h1>
<%= link_to 'New Spot', new_spot_path %>
<table>
	<thead>
		<tr>
			<th>Spot Name</th>
			<th>Nearest entry</th>
			<th>Occupied</th>
			<th>Parking</th>
			<th colspan="3">Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @spots.each do |spot| %>
			<tr>
				<td><%= spot.name %></td>
				<td><%= spot.nearest_entry %></td>
				<td><%= spot.occupied %></td>
				<td><%= spot.parking.name %></td>
				<td><%= link_to 'View', spot %></td>
				<td><%= link_to 'Edit', edit_spot_path(spot) %></td>
				<td><%= link_to 'Delete', spot, data: { "turbo-method": :delete } %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/spots/new.html.erb
<h1>new spot</h1>

<%= render "form", spot: @spot %>

app/views/spots/show.html.erb
<h1>spot details</h1>

<p><strong>Spot Name: </strong><%= @spot.name %></p><br>
<p><strong>Nearest Entry: </strong><%= @spot.nearest_entry %></p><br>
<p><strong>Oppuied: </strong><%= @spot.occupied %></p><br>
<p><strong>Parking Name: </strong><%= @spot.parking_id %></p><br>



<%= link_to 'Back', spots_path %> | <td><%= link_to 'Edit', edit_spot_path(@spot) %></td>

app/views/tickets/_form.html.erb
<%= form_with scope: ticket, url: tickets_path do |form| %>

	<% if @ticket.errors.any? %>
		<% @ticket.errors.full_messages.each do |message| %>
			<p><%= message %></p>
		<% end %>
	<% end %>

	<!-- <div> -->
		<%#= form.label :time_arrival %>
		<%#= form.text_field :time_arrival %>
	<!-- </div><br> 
	<div> -->
		<%#= form.label :time_departure %>
		<%#= form.text_field :time_departure %>
	<!-- </div><br>  -->
	<!-- <div>  --><!--
		<%#= form.label :ticket_number %>
		<%#= form.text_field :ticket_number %>
	</div><br> -->
	<div>
		<%= form.label :parking %>
		<%= form.select :parking, parking_options, include_blank: false, required: true %>
	</div><br> 
	<div>
		<%= form.label :registration_number %>
		<%= form.collection_select :car_id, Car.not_in_parking.order(:name), :id, :registration_number, prompt: 'Select Registration No', required: true %>
	</div><br>
<!-- 	<div>
		<%#= form.label :car_id %>
		<%#= form.text_field :car_id %>
	</div><br>
	<div>
		<%#= form.label :spot_id %>
		<%#= form.text_field :spot_id %>
	</div><br>  -->

	<div>
		<%= form.submit %>
	</div>
	
<% end %>

app/views/tickets/edit.html.erb
<h1>Edit Ticket</h1>

<%= render "form", ticket: @ticket %>

app/views/tickets/index.html.erb
<h1>All Ticket</h1>
<%= link_to 'New Ticket', new_ticket_path %>
<table>
	<thead>
		<tr>
			<th>Arrival time</th>
			<th>Departure time</th>
			<th>Ticket number</th>
			<th>Spot</th>
			<th>Car</th>
			<th colspan="4">Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @tickets.each do |ticket| %>
			<tr>
				<td><%= ticket.time_arrival %></td>
				<td><%= ticket.time_departure %></td>
				<td><%= ticket.ticket_number %></td>
				<td><%= ticket.spot.name %></td>
				<td><%= ticket.car.registration_number %></td>
				<td><%= link_to 'View', ticket %></td>
				<td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
				<td><%= link_to 'Delete', ticket, data: { "turbo-method": :delete } %></td>
				<td><%= link_to 'CheckOut', checkout_ticket_path(ticket), data: { "turbo-method": :put } %></td>		
			</tr>
		<% end %>
	</tbody>
</table>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render "form", ticket: @ticket %>